version: "3.1"

services:
    ssl:
        container_name: ssl
        restart: always
        image: labdocodigo/ssl
        volumes:
            - "./config/ssl/nginx.conf:/etc/nginx/nginx.conf"
            - "./config/ssl/mime.types:/etc/nginx/mime.types"
            - "./config/ssl/default.conf:/etc/nginx/conf.d/default.conf"
            - "./config/ssl/key/:/etc/ssl/"
            - "./config/ssl/naxsi_core.rules:/etc/nginx/naxsi_core.rules"
            - "./config/ssl/naxsi.rules:/etc/nginx/naxsi.rules"
            - "./log/ssl/:/var/log/nginx/"
            - "./src/:/var/www/html/"
        ports:
            - "80:80"
            - "443:443"
        links:
            - varnish
            - web
        depends_on:
            - varnish
            - web

    varnish:
        container_name: varnish
        restart: always
        image: labdocodigo/varnish
        volumes:
            - "./config/varnish:/etc/default/varnish"
            - "./config/varnish/default.vcl:/etc/varnish/default.vcl"
        links:
            - web
        depends_on:
            - web

    web:
        container_name: web
        restart: always
        image: labdocodigo/web
        volumes:
            - "./config/web/nginx.conf:/etc/nginx/nginx.conf"
            - "./config/web/mime.types:/etc/nginx/mime.types"
            - "./config/web/default.conf:/etc/nginx/conf.d/default.conf"
            - "./log/web/:/var/log/nginx/"
            - "./src/:/var/www/html/"
        depends_on:
            - php

    php:
        container_name: php
        restart: always
        image: labdocodigo/php
        volumes:
            - "./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
            - "./config/php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf"
            - "./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "./config/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf"
            - "./log/php/:/var/log/"
            - "./src/:/var/www/html/"
        links:
            - postgresql
        depends_on:
            - postgresql

    postgresql:
        container_name: postgresql
        restart: always
        image: postgres:11-alpine
        environment:
            - POSTGRES_DB=superhype
            - POSTGRES_USER=superhype
            - POSTGRES_PASSWORD=Jeremias3374
        volumes:
            - "./config/postgresql/:/etc/postgresql/"
            - "postgresql:/var/lib/postgresql/data/"
        ports:
            - "5432:5432"

volumes:
    postgresql: